version: '3.8'

services:
  malware_attacker:
    build: .
    container_name: malware_attacker
    networks:
      custom_net:
        ipv4_address: 192.168.6.200
    environment:
      - TARGET_IP=192.168.6.131
      - TARGET_PORT=5000
      - C2_BEACON_INTERVAL=1
      - EXFIL_INTERVAL=2
      - EICAR_INTERVAL=2
      - DNS_ATTACK_INTERVAL=2
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

networks:
  custom_net:
    external: true
