version: '3.8'

services:
  malware_attacker:
    build: .
    container_name: malware_attacker
    networks:
      custom_net:
        ipv4_address: 192.168.6.200
    environment:
      - TARGET_IP=192.168.6.131
      - TARGET_PORT=5000
      - UPLOAD_INTERVAL=5
    volumes:
      - ./logs:/app/logs
      - ../../a864d996cb6607a470469d9192cfb8abd3797a8ad90bea7ce00caa1195b40e5f.apk:/app/sample.apk
    restart: unless-stopped

networks:
  custom_net:
    external: true
